### PR TITLE
Closes #47: Got a show page for items working. Also pulled down unmerged branches, fixed conflicts, and consolidated everything

### LINKED ISSUE #10: 10. Guest User
As a visitor when I have items in my cart And when I visit “/cart” I should not see an option to “Checkout” I should see an option to “Login or Create Account to Checkout” After I create an account And I visit “/cart Then I should see all of the data that was there when I was not logged in

### LINKED ISSUE #47: item show page
make a show

### PR DESCRIPTION
**Pull request by Aram-Anderson**
#### Issue Number: 
47
#### Description of changes:
Changed seed file to work with enum on item model, and added some country name tags to seeds, and gave each item more than one seed. Refactored view for index to make it more badass. Merged in all branches that are up on github from other collaborators.

# We need to dial in the git workflow, push and make PRs more frequently. There were fresh branches on github that were more than 10 commits behind master. Pull from master every time there is a merge!

#### @mentions of the person or team responsible for reviewing proposed changes:
@dphilla @mikeyduece @liambarstad

### CODE REVIEW

File: db/schema.rb [hunk 1]
```diff
@@ -26,19 +26,30 @@
...
     t.datetime "created_at", null: false
     t.datetime "updated_at", null: false
   end
 
+  create_table "order_items", force: :cascade do |t|
+    t.bigint "item_id"
+    t.bigint "order_id"
+    t.datetime "created_at", null: false
+    t.datetime "updated_at", null: false
+    t.integer "quantity"
```
Comment (Aram-Anderson) [inline db/schema.rb]: I don't really think this should be here. We can get this info through the relationship, without the extra column on the join.

File: db/schema.rb [hunk 2]
```diff
@@ -26,19 +26,30 @@
...
+    t.index ["item_id"], name: "index_order_items_on_item_id"
+    t.index ["order_id"], name: "index_order_items_on_order_id"
+  end
+
   create_table "orders", force: :cascade do |t|
     t.bigint "user_id"
     t.integer "status", default: 0
     t.datetime "created_at", null: false
     t.datetime "updated_at", null: false
+    t.float "total_price"
```
Comment (Aram-Anderson) [inline db/schema.rb]: Same here.

File: db/items.csv [hunk 3]
```diff
@@ -37,5 +37,4 @@ Fleur de Lis Salt & Pepper Shakers,"Each Fleur De Lis Salt & Pepper Shaker is ha
...
 Vintage Stone Cement Salt Jar,"Old style salt box, that can be either wall mounted or placed on a counter.  Typical of the ones seen in old kitchens in France and Northern Europe.  It's 3 inches in diameter and 3.5 inches high.",995,0,http://thecrossdesign.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/t/stone_cement_jar_2_1024x1024.jpg
-Stoneware & Cork salt & Pepper Shakers,This set of 2 pig shaped salt and pepper shakers will be happy to grace your dinner table.,999,0,https://www.touchofeurope.net/thumbnail.asp?file=assets/images/stonewarecorkpigsaltpeppershakerswhitesetof2.jpg&maxx=50&maxy=0
-Steampunk Pepper Mill,The hand-crank design of this finely handcrafted heirloom pepper mill was inspired by antique chef's tools.,9800,0,https://i.pinimg.com/564x/71/6f/67/716f67b26761c559586efd2d9acfd34f.jpg
\ No newline at end of file
+Steampunk Pepper Mill,The hand-crank design of this finely handcrafted heirloom pepper mill was inspired by antique chef's tools.,9800,0,https://i.pinimg.com/564x/71/6f/67/716f67b26761c559586efd2d9acfd34f.jpg
```
Comment (Aram-Anderson) [inline db/items.csv:40]: I didn't really change anything here, I was just trying to find a higher resolution image for this one item, but it didn't work right.

File: db/seeds.rb [hunk 4]
```diff
@@ -14,25 +14,26 @@
...
+ Tag.create(name: "Pink")
+ Tag.create(name: "Flake")
+ Tag.create(name: "Coarse")
+ Tag.create(name: "Fine")
+ Tag.create(name: "accessories")
+ Tag.create(name: "salt")
+ 20.times do
+  Tag.create(name: Faker::Address.unique.country)
+ end
+
```
Comment (Aram-Anderson) [inline db/seeds.rb:33]: Sorry to jump in on the seed file, @dphilla and @mikeyduece , I changed it so we had more tags, and more than one tag per item.

File: spec/factories/order_items.rb [hunk 5]
```diff
@@ -0,0 +1,7 @@
+FactoryGirl.define do
```
Comment (Aram-Anderson) [inline spec/factories/order_items.rb]: We don't need a factory for a joins table. That's the point of a joins table.

File: spec/features/orders/user_can_view_single_order_page_spec.rb [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+    user = create(:user)
+    visit root_path
+    click_on("Login")
+    fill_in "user[name]", with: user.name
+    fill_in "user[password]", with: "Password"
+    click_on("Log in")
+    
+    order = create(:order, user: user)
+    item = create(:item)
+    order_item = create(:order_item, order: order, item: item)
```
Comment (Aram-Anderson) [inline spec/features/orders/user_can_view_single_order_page_spec.rb]: We shouldn't be creating joins entries manually. Using the relationship does that automatically.

**Review by Aram-Anderson — COMMENTED** [review]
There's some refactoring to do, but I think we should merge this in so we're all on the same version of the app. There is quite a bit of divergence between the branches we're locally working on. Let's do a merge and have everyone pull down.

File: db/seeds.rb (hunk 4 above)
Comment (mikeheft) [reply db/seeds.rb:33]: No worries. We just did it that way so they all had at least one, since we need to add the functionality for the admin to add tags anyway

File: db/schema.rb (hunk 1 above)
Comment (mikeheft) [reply db/schema.rb]: Are you saying that if we fill the cart with three same items, and checkout that each would be it's own row on the OrderItem table?

File: db/schema.rb (hunk 2 above)
Comment (mikeheft) [reply db/schema.rb]: I think total price is fine here. How else would we be able to call total price for that order? Unless that's not something we need to have as a column and instead just an instance method that can be called in the view?

File: spec/features/orders/user_can_view_single_order_page_spec.rb (hunk 6 above)
Comment (mikeheft) [reply spec/features/orders/user_can_view_single_order_page_spec.rb]: This was Liam's test. But can you walk me through the factory stuff with regards to joins tables? They're still giving me problems on other projects

**Review by mikeheft — APPROVED** [review]
Looks good to me. I agree with @Aram-Anderson but would still like to maybe talk it out before refactor.

File: db/migrate/20170914235746_add_quantity_to_order_items.rb [hunk 7]
```diff
@@ -0,0 +1,5 @@
+class AddQuantityToOrderItems < ActiveRecord::Migration[5.1]
+  def change
+    add_column :order_items, :quantity, :integer
```
Comment (dphilla) [inline db/migrate/20170914235746_add_quantity_to_order_items.rb]: What's the reasoning of doing this here and not as a method on the Order model or Cart Poro?

File: db/schema.rb (hunk 1 above)
Comment (dphilla) [reply db/schema.rb]: Yeah I think that we could move that to work at the model level--code smell here seems to be off to me.

**Review by dphilla — APPROVED** [review]
